"""
GENERATED FILE - do not edit by hand.  Regenerate with:

    python3 tools/make_seasonal_geo.py

Offline timezone geography for the seasonal themes (cubeon/seasonal.py). All of
this is derived data from the public-domain IANA tz database + iso-codes; it is
committed so a shipped Cubeon knows where its user is without reading
/usr/share/zoneinfo (absent on Windows) and without a network call.

How the classification is made:
  * ZONE_COUNTRY - the ISO-3166 country of an IANA zone (zone.tab column 1).
  * SOUTH_ZONES  - zones whose representative latitude is south of the equator.
  * TROPIC_ZONES - |latitude| <= 23.5, where the four-season model does not
                   apply: those users get a wet/dry season (see seasonal.py)
                   instead of a fake "autumn".
  * WIN_ZONES    - Windows zone names (tzutil /g) mapped to IANA, trimmed to the
                   entries where being wrong would visibly mis-theme someone.
Anything not listed is assumed northern/temperate - the right guess for ~87% of
people, and always overridable in Settings > Seasonal.

Sources: zone.tab (+418), zone1970.tab (+0) and iso_3166-1 (country names).
"""

GENERATED_AT = "2026-09-17"


ZONE_COUNTRY = {
    "Africa/Abidjan": "CI", "Africa/Accra": "GH", "Africa/Addis_Ababa": "ET",
    "Africa/Algiers": "DZ", "Africa/Asmara": "ER", "Africa/Bamako": "ML",
    "Africa/Bangui": "CF", "Africa/Banjul": "GM", "Africa/Bissau": "GW",
    "Africa/Blantyre": "MW", "Africa/Brazzaville": "CG", "Africa/Bujumbura": "BI",
    "Africa/Cairo": "EG", "Africa/Casablanca": "MA", "Africa/Ceuta": "ES",
    "Africa/Conakry": "GN", "Africa/Dakar": "SN", "Africa/Dar_es_Salaam": "TZ",
    "Africa/Djibouti": "DJ", "Africa/Douala": "CM", "Africa/El_Aaiun": "EH",
    "Africa/Freetown": "SL", "Africa/Gaborone": "BW", "Africa/Harare": "ZW",
    "Africa/Johannesburg": "ZA", "Africa/Juba": "SS", "Africa/Kampala": "UG",
    "Africa/Khartoum": "SD", "Africa/Kigali": "RW", "Africa/Kinshasa": "CD",
    "Africa/Lagos": "NG", "Africa/Libreville": "GA", "Africa/Lome": "TG",
    "Africa/Luanda": "AO", "Africa/Lubumbashi": "CD", "Africa/Lusaka": "ZM",
    "Africa/Malabo": "GQ", "Africa/Maputo": "MZ", "Africa/Maseru": "LS",
    "Africa/Mbabane": "SZ", "Africa/Mogadishu": "SO", "Africa/Monrovia": "LR",
    "Africa/Nairobi": "KE", "Africa/Ndjamena": "TD", "Africa/Niamey": "NE",
    "Africa/Nouakchott": "MR", "Africa/Ouagadougou": "BF", "Africa/Porto-Novo": "BJ",
    "Africa/Sao_Tome": "ST", "Africa/Tripoli": "LY", "Africa/Tunis": "TN",
    "Africa/Windhoek": "NA", "America/Adak": "US", "America/Anchorage": "US",
    "America/Anguilla": "AI", "America/Antigua": "AG", "America/Araguaina": "BR",
    "America/Argentina/Buenos_Aires": "AR", "America/Argentina/Catamarca": "AR", "America/Argentina/Cordoba": "AR",
    "America/Argentina/Jujuy": "AR", "America/Argentina/La_Rioja": "AR", "America/Argentina/Mendoza": "AR",
    "America/Argentina/Rio_Gallegos": "AR", "America/Argentina/Salta": "AR", "America/Argentina/San_Juan": "AR",
    "America/Argentina/San_Luis": "AR", "America/Argentina/Tucuman": "AR", "America/Argentina/Ushuaia": "AR",
    "America/Aruba": "AW", "America/Asuncion": "PY", "America/Atikokan": "CA",
    "America/Bahia": "BR", "America/Bahia_Banderas": "MX", "America/Barbados": "BB",
    "America/Belem": "BR", "America/Belize": "BZ", "America/Blanc-Sablon": "CA",
    "America/Boa_Vista": "BR", "America/Bogota": "CO", "America/Boise": "US",
    "America/Cambridge_Bay": "CA", "America/Campo_Grande": "BR", "America/Cancun": "MX",
    "America/Caracas": "VE", "America/Cayenne": "GF", "America/Cayman": "KY",
    "America/Chicago": "US", "America/Chihuahua": "MX", "America/Ciudad_Juarez": "MX",
    "America/Costa_Rica": "CR", "America/Coyhaique": "CL", "America/Creston": "CA",
    "America/Cuiaba": "BR", "America/Curacao": "CW", "America/Danmarkshavn": "GL",
    "America/Dawson": "CA", "America/Dawson_Creek": "CA", "America/Denver": "US",
    "America/Detroit": "US", "America/Dominica": "DM", "America/Edmonton": "CA",
    "America/Eirunepe": "BR", "America/El_Salvador": "SV", "America/Fort_Nelson": "CA",
    "America/Fortaleza": "BR", "America/Glace_Bay": "CA", "America/Goose_Bay": "CA",
    "America/Grand_Turk": "TC", "America/Grenada": "GD", "America/Guadeloupe": "GP",
    "America/Guatemala": "GT", "America/Guayaquil": "EC", "America/Guyana": "GY",
    "America/Halifax": "CA", "America/Havana": "CU", "America/Hermosillo": "MX",
    "America/Indiana/Indianapolis": "US", "America/Indiana/Knox": "US", "America/Indiana/Marengo": "US",
    "America/Indiana/Petersburg": "US", "America/Indiana/Tell_City": "US", "America/Indiana/Vevay": "US",
    "America/Indiana/Vincennes": "US", "America/Indiana/Winamac": "US", "America/Inuvik": "CA",
    "America/Iqaluit": "CA", "America/Jamaica": "JM", "America/Juneau": "US",
    "America/Kentucky/Louisville": "US", "America/Kentucky/Monticello": "US", "America/Kralendijk": "BQ",
    "America/La_Paz": "BO", "America/Lima": "PE", "America/Los_Angeles": "US",
    "America/Lower_Princes": "SX", "America/Maceio": "BR", "America/Managua": "NI",
    "America/Manaus": "BR", "America/Marigot": "MF", "America/Martinique": "MQ",
    "America/Matamoros": "MX", "America/Mazatlan": "MX", "America/Menominee": "US",
    "America/Merida": "MX", "America/Metlakatla": "US", "America/Mexico_City": "MX",
    "America/Miquelon": "PM", "America/Moncton": "CA", "America/Monterrey": "MX",
    "America/Montevideo": "UY", "America/Montserrat": "MS", "America/Nassau": "BS",
    "America/New_York": "US", "America/Nome": "US", "America/Noronha": "BR",
    "America/North_Dakota/Beulah": "US", "America/North_Dakota/Center": "US", "America/North_Dakota/New_Salem": "US",
    "America/Nuuk": "GL", "America/Ojinaga": "MX", "America/Panama": "PA",
    "America/Paramaribo": "SR", "America/Phoenix": "US", "America/Port-au-Prince": "HT",
    "America/Port_of_Spain": "TT", "America/Porto_Velho": "BR", "America/Puerto_Rico": "PR",
    "America/Punta_Arenas": "CL", "America/Rankin_Inlet": "CA", "America/Recife": "BR",
    "America/Regina": "CA", "America/Resolute": "CA", "America/Rio_Branco": "BR",
    "America/Santarem": "BR", "America/Santiago": "CL", "America/Santo_Domingo": "DO",
    "America/Sao_Paulo": "BR", "America/Scoresbysund": "GL", "America/Sitka": "US",
    "America/St_Barthelemy": "BL", "America/St_Johns": "CA", "America/St_Kitts": "KN",
    "America/St_Lucia": "LC", "America/St_Thomas": "VI", "America/St_Vincent": "VC",
    "America/Swift_Current": "CA", "America/Tegucigalpa": "HN", "America/Thule": "GL",
    "America/Tijuana": "MX", "America/Toronto": "CA", "America/Tortola": "VG",
    "America/Vancouver": "CA", "America/Whitehorse": "CA", "America/Winnipeg": "CA",
    "America/Yakutat": "US", "Antarctica/Casey": "AQ", "Antarctica/Davis": "AQ",
    "Antarctica/DumontDUrville": "AQ", "Antarctica/Macquarie": "AU", "Antarctica/Mawson": "AQ",
    "Antarctica/McMurdo": "AQ", "Antarctica/Palmer": "AQ", "Antarctica/Rothera": "AQ",
    "Antarctica/Syowa": "AQ", "Antarctica/Troll": "AQ", "Antarctica/Vostok": "AQ",
    "Arctic/Longyearbyen": "SJ", "Asia/Aden": "YE", "Asia/Almaty": "KZ",
    "Asia/Amman": "JO", "Asia/Anadyr": "RU", "Asia/Aqtau": "KZ",
    "Asia/Aqtobe": "KZ", "Asia/Ashgabat": "TM", "Asia/Atyrau": "KZ",
    "Asia/Baghdad": "IQ", "Asia/Bahrain": "BH", "Asia/Baku": "AZ",
    "Asia/Bangkok": "TH", "Asia/Barnaul": "RU", "Asia/Beirut": "LB",
    "Asia/Bishkek": "KG", "Asia/Brunei": "BN", "Asia/Chita": "RU",
    "Asia/Colombo": "LK", "Asia/Damascus": "SY", "Asia/Dhaka": "BD",
    "Asia/Dili": "TL", "Asia/Dubai": "AE", "Asia/Dushanbe": "TJ",
    "Asia/Famagusta": "CY", "Asia/Gaza": "PS", "Asia/Hebron": "PS",
    "Asia/Ho_Chi_Minh": "VN", "Asia/Hong_Kong": "HK", "Asia/Hovd": "MN",
    "Asia/Irkutsk": "RU", "Asia/Jakarta": "ID", "Asia/Jayapura": "ID",
    "Asia/Jerusalem": "IL", "Asia/Kabul": "AF", "Asia/Kamchatka": "RU",
    "Asia/Karachi": "PK", "Asia/Kathmandu": "NP", "Asia/Khandyga": "RU",
    "Asia/Kolkata": "IN", "Asia/Krasnoyarsk": "RU", "Asia/Kuala_Lumpur": "MY",
    "Asia/Kuching": "MY", "Asia/Kuwait": "KW", "Asia/Macau": "MO",
    "Asia/Magadan": "RU", "Asia/Makassar": "ID", "Asia/Manila": "PH",
    "Asia/Muscat": "OM", "Asia/Nicosia": "CY", "Asia/Novokuznetsk": "RU",
    "Asia/Novosibirsk": "RU", "Asia/Omsk": "RU", "Asia/Oral": "KZ",
    "Asia/Phnom_Penh": "KH", "Asia/Pontianak": "ID", "Asia/Pyongyang": "KP",
    "Asia/Qatar": "QA", "Asia/Qostanay": "KZ", "Asia/Qyzylorda": "KZ",
    "Asia/Riyadh": "SA", "Asia/Sakhalin": "RU", "Asia/Samarkand": "UZ",
    "Asia/Seoul": "KR", "Asia/Shanghai": "CN", "Asia/Singapore": "SG",
    "Asia/Srednekolymsk": "RU", "Asia/Taipei": "TW", "Asia/Tashkent": "UZ",
    "Asia/Tbilisi": "GE", "Asia/Tehran": "IR", "Asia/Thimphu": "BT",
    "Asia/Tokyo": "JP", "Asia/Tomsk": "RU", "Asia/Ulaanbaatar": "MN",
    "Asia/Urumqi": "CN", "Asia/Ust-Nera": "RU", "Asia/Vientiane": "LA",
    "Asia/Vladivostok": "RU", "Asia/Yakutsk": "RU", "Asia/Yangon": "MM",
    "Asia/Yekaterinburg": "RU", "Asia/Yerevan": "AM", "Atlantic/Azores": "PT",
    "Atlantic/Bermuda": "BM", "Atlantic/Canary": "ES", "Atlantic/Cape_Verde": "CV",
    "Atlantic/Faroe": "FO", "Atlantic/Madeira": "PT", "Atlantic/Reykjavik": "IS",
    "Atlantic/South_Georgia": "GS", "Atlantic/St_Helena": "SH", "Atlantic/Stanley": "FK",
    "Australia/Adelaide": "AU", "Australia/Brisbane": "AU", "Australia/Broken_Hill": "AU",
    "Australia/Darwin": "AU", "Australia/Eucla": "AU", "Australia/Hobart": "AU",
    "Australia/Lindeman": "AU", "Australia/Lord_Howe": "AU", "Australia/Melbourne": "AU",
    "Australia/Perth": "AU", "Australia/Sydney": "AU", "Europe/Amsterdam": "NL",
    "Europe/Andorra": "AD", "Europe/Astrakhan": "RU", "Europe/Athens": "GR",
    "Europe/Belgrade": "RS", "Europe/Berlin": "DE", "Europe/Bratislava": "SK",
    "Europe/Brussels": "BE", "Europe/Bucharest": "RO", "Europe/Budapest": "HU",
    "Europe/Busingen": "DE", "Europe/Chisinau": "MD", "Europe/Copenhagen": "DK",
    "Europe/Dublin": "IE", "Europe/Gibraltar": "GI", "Europe/Guernsey": "GG",
    "Europe/Helsinki": "FI", "Europe/Isle_of_Man": "IM", "Europe/Istanbul": "TR",
    "Europe/Jersey": "JE", "Europe/Kaliningrad": "RU", "Europe/Kirov": "RU",
    "Europe/Kyiv": "UA", "Europe/Lisbon": "PT", "Europe/Ljubljana": "SI",
    "Europe/London": "GB", "Europe/Luxembourg": "LU", "Europe/Madrid": "ES",
    "Europe/Malta": "MT", "Europe/Mariehamn": "AX", "Europe/Minsk": "BY",
    "Europe/Monaco": "MC", "Europe/Moscow": "RU", "Europe/Oslo": "NO",
    "Europe/Paris": "FR", "Europe/Podgorica": "ME", "Europe/Prague": "CZ",
    "Europe/Riga": "LV", "Europe/Rome": "IT", "Europe/Samara": "RU",
    "Europe/San_Marino": "SM", "Europe/Sarajevo": "BA", "Europe/Saratov": "RU",
    "Europe/Simferopol": "UA", "Europe/Skopje": "MK", "Europe/Sofia": "BG",
    "Europe/Stockholm": "SE", "Europe/Tallinn": "EE", "Europe/Tirane": "AL",
    "Europe/Ulyanovsk": "RU", "Europe/Vaduz": "LI", "Europe/Vatican": "VA",
    "Europe/Vienna": "AT", "Europe/Vilnius": "LT", "Europe/Volgograd": "RU",
    "Europe/Warsaw": "PL", "Europe/Zagreb": "HR", "Europe/Zurich": "CH",
    "Indian/Antananarivo": "MG", "Indian/Chagos": "IO", "Indian/Christmas": "CX",
    "Indian/Cocos": "CC", "Indian/Comoro": "KM", "Indian/Kerguelen": "TF",
    "Indian/Mahe": "SC", "Indian/Maldives": "MV", "Indian/Mauritius": "MU",
    "Indian/Mayotte": "YT", "Indian/Reunion": "RE", "Pacific/Apia": "WS",
    "Pacific/Auckland": "NZ", "Pacific/Bougainville": "PG", "Pacific/Chatham": "NZ",
    "Pacific/Chuuk": "FM", "Pacific/Easter": "CL", "Pacific/Efate": "VU",
    "Pacific/Fakaofo": "TK", "Pacific/Fiji": "FJ", "Pacific/Funafuti": "TV",
    "Pacific/Galapagos": "EC", "Pacific/Gambier": "PF", "Pacific/Guadalcanal": "SB",
    "Pacific/Guam": "GU", "Pacific/Honolulu": "US", "Pacific/Kanton": "KI",
    "Pacific/Kiritimati": "KI", "Pacific/Kosrae": "FM", "Pacific/Kwajalein": "MH",
    "Pacific/Majuro": "MH", "Pacific/Marquesas": "PF", "Pacific/Midway": "UM",
    "Pacific/Nauru": "NR", "Pacific/Niue": "NU", "Pacific/Norfolk": "NF",
    "Pacific/Noumea": "NC", "Pacific/Pago_Pago": "AS", "Pacific/Palau": "PW",
    "Pacific/Pitcairn": "PN", "Pacific/Pohnpei": "FM", "Pacific/Port_Moresby": "PG",
    "Pacific/Rarotonga": "CK", "Pacific/Saipan": "MP", "Pacific/Tahiti": "PF",
    "Pacific/Tarawa": "KI", "Pacific/Tongatapu": "TO", "Pacific/Wake": "UM",
    "Pacific/Wallis": "WF",
}


COUNTRY_NAME = {
    "AD": "Andorra", "AE": "United Arab Emirates", "AF": "Afghanistan",
    "AG": "Antigua and Barbuda", "AI": "Anguilla", "AL": "Albania",
    "AM": "Armenia", "AO": "Angola", "AQ": "Antarctica",
    "AR": "Argentina", "AS": "American Samoa", "AT": "Austria",
    "AU": "Australia", "AW": "Aruba", "AX": "Åland Islands",
    "AZ": "Azerbaijan", "BA": "Bosnia and Herzegovina", "BB": "Barbados",
    "BD": "Bangladesh", "BE": "Belgium", "BF": "Burkina Faso",
    "BG": "Bulgaria", "BH": "Bahrain", "BI": "Burundi",
    "BJ": "Benin", "BL": "Saint Barthélemy", "BM": "Bermuda",
    "BN": "Brunei Darussalam", "BO": "Bolivia, Plurinational State of", "BQ": "Bonaire, Sint Eustatius and Saba",
    "BR": "Brazil", "BS": "Bahamas", "BT": "Bhutan",
    "BW": "Botswana", "BY": "Belarus", "BZ": "Belize",
    "CA": "Canada", "CC": "Cocos (Keeling) Islands", "CD": "Congo, The Democratic Republic of the",
    "CF": "Central African Republic", "CG": "Congo", "CH": "Switzerland",
    "CI": "Côte d'Ivoire", "CK": "Cook Islands", "CL": "Chile",
    "CM": "Cameroon", "CN": "China", "CO": "Colombia",
    "CR": "Costa Rica", "CU": "Cuba", "CV": "Cabo Verde",
    "CW": "Curaçao", "CX": "Christmas Island", "CY": "Cyprus",
    "CZ": "Czechia", "DE": "Germany", "DJ": "Djibouti",
    "DK": "Denmark", "DM": "Dominica", "DO": "Dominican Republic",
    "DZ": "Algeria", "EC": "Ecuador", "EE": "Estonia",
    "EG": "Egypt", "EH": "Western Sahara", "ER": "Eritrea",
    "ES": "Spain", "ET": "Ethiopia", "FI": "Finland",
    "FJ": "Fiji", "FK": "Falkland Islands (Malvinas)", "FM": "Micronesia, Federated States of",
    "FO": "Faroe Islands", "FR": "France", "GA": "Gabon",
    "GB": "United Kingdom", "GD": "Grenada", "GE": "Georgia",
    "GF": "French Guiana", "GG": "Guernsey", "GH": "Ghana",
    "GI": "Gibraltar", "GL": "Greenland", "GM": "Gambia",
    "GN": "Guinea", "GP": "Guadeloupe", "GQ": "Equatorial Guinea",
    "GR": "Greece", "GS": "South Georgia and the South Sandwich Islands", "GT": "Guatemala",
    "GU": "Guam", "GW": "Guinea-Bissau", "GY": "Guyana",
    "HK": "Hong Kong", "HN": "Honduras", "HR": "Croatia",
    "HT": "Haiti", "HU": "Hungary", "ID": "Indonesia",
    "IE": "Ireland", "IL": "Israel", "IM": "Isle of Man",
    "IN": "India", "IO": "British Indian Ocean Territory", "IQ": "Iraq",
    "IR": "Iran, Islamic Republic of", "IS": "Iceland", "IT": "Italy",
    "JE": "Jersey", "JM": "Jamaica", "JO": "Jordan",
    "JP": "Japan", "KE": "Kenya", "KG": "Kyrgyzstan",
    "KH": "Cambodia", "KI": "Kiribati", "KM": "Comoros",
    "KN": "Saint Kitts and Nevis", "KP": "Korea, Democratic People's Republic of", "KR": "Korea, Republic of",
    "KW": "Kuwait", "KY": "Cayman Islands", "KZ": "Kazakhstan",
    "LA": "Lao People's Democratic Republic", "LB": "Lebanon", "LC": "Saint Lucia",
    "LI": "Liechtenstein", "LK": "Sri Lanka", "LR": "Liberia",
    "LS": "Lesotho", "LT": "Lithuania", "LU": "Luxembourg",
    "LV": "Latvia", "LY": "Libya", "MA": "Morocco",
    "MC": "Monaco", "MD": "Moldova, Republic of", "ME": "Montenegro",
    "MF": "Saint Martin (French part)", "MG": "Madagascar", "MH": "Marshall Islands",
    "MK": "North Macedonia", "ML": "Mali", "MM": "Myanmar",
    "MN": "Mongolia", "MO": "Macao", "MP": "Northern Mariana Islands",
    "MQ": "Martinique", "MR": "Mauritania", "MS": "Montserrat",
    "MT": "Malta", "MU": "Mauritius", "MV": "Maldives",
    "MW": "Malawi", "MX": "Mexico", "MY": "Malaysia",
    "MZ": "Mozambique", "NA": "Namibia", "NC": "New Caledonia",
    "NE": "Niger", "NF": "Norfolk Island", "NG": "Nigeria",
    "NI": "Nicaragua", "NL": "Netherlands", "NO": "Norway",
    "NP": "Nepal", "NR": "Nauru", "NU": "Niue",
    "NZ": "New Zealand", "OM": "Oman", "PA": "Panama",
    "PE": "Peru", "PF": "French Polynesia", "PG": "Papua New Guinea",
    "PH": "Philippines", "PK": "Pakistan", "PL": "Poland",
    "PM": "Saint Pierre and Miquelon", "PN": "Pitcairn", "PR": "Puerto Rico",
    "PS": "Palestine, State of", "PT": "Portugal", "PW": "Palau",
    "PY": "Paraguay", "QA": "Qatar", "RE": "Réunion",
    "RO": "Romania", "RS": "Serbia", "RU": "Russian Federation",
    "RW": "Rwanda", "SA": "Saudi Arabia", "SB": "Solomon Islands",
    "SC": "Seychelles", "SD": "Sudan", "SE": "Sweden",
    "SG": "Singapore", "SH": "Saint Helena, Ascension and Tristan da Cunha", "SI": "Slovenia",
    "SJ": "Svalbard and Jan Mayen", "SK": "Slovakia", "SL": "Sierra Leone",
    "SM": "San Marino", "SN": "Senegal", "SO": "Somalia",
    "SR": "Suriname", "SS": "South Sudan", "ST": "Sao Tome and Principe",
    "SV": "El Salvador", "SX": "Sint Maarten (Dutch part)", "SY": "Syrian Arab Republic",
    "SZ": "Eswatini", "TC": "Turks and Caicos Islands", "TD": "Chad",
    "TF": "French Southern Territories", "TG": "Togo", "TH": "Thailand",
    "TJ": "Tajikistan", "TK": "Tokelau", "TL": "Timor-Leste",
    "TM": "Turkmenistan", "TN": "Tunisia", "TO": "Tonga",
    "TR": "Türkiye", "TT": "Trinidad and Tobago", "TV": "Tuvalu",
    "TW": "Taiwan, Province of China", "TZ": "Tanzania, United Republic of", "UA": "Ukraine",
    "UG": "Uganda", "UM": "United States Minor Outlying Islands", "US": "United States",
    "UY": "Uruguay", "UZ": "Uzbekistan", "VA": "Holy See (Vatican City State)",
    "VC": "Saint Vincent and the Grenadines", "VE": "Venezuela, Bolivarian Republic of", "VG": "Virgin Islands, British",
    "VI": "Virgin Islands, U.S.", "VN": "Viet Nam", "VU": "Vanuatu",
    "WF": "Wallis and Futuna", "WS": "Samoa", "YE": "Yemen",
    "YT": "Mayotte", "ZA": "South Africa", "ZM": "Zambia",
    "ZW": "Zimbabwe",
}


SOUTH_ZONES = frozenset({
    "Africa/Blantyre", "Africa/Brazzaville", "Africa/Bujumbura",
    "Africa/Dar_es_Salaam", "Africa/Gaborone", "Africa/Harare",
    "Africa/Johannesburg", "Africa/Kigali", "Africa/Kinshasa",
    "Africa/Luanda", "Africa/Lubumbashi", "Africa/Lusaka",
    "Africa/Maputo", "Africa/Maseru", "Africa/Mbabane",
    "Africa/Nairobi", "Africa/Windhoek", "America/Araguaina",
    "America/Argentina/Buenos_Aires", "America/Argentina/Catamarca", "America/Argentina/Cordoba",
    "America/Argentina/Jujuy", "America/Argentina/La_Rioja", "America/Argentina/Mendoza",
    "America/Argentina/Rio_Gallegos", "America/Argentina/Salta", "America/Argentina/San_Juan",
    "America/Argentina/San_Luis", "America/Argentina/Tucuman", "America/Argentina/Ushuaia",
    "America/Asuncion", "America/Bahia", "America/Belem",
    "America/Campo_Grande", "America/Coyhaique", "America/Cuiaba",
    "America/Eirunepe", "America/Fortaleza", "America/Guayaquil",
    "America/La_Paz", "America/Lima", "America/Maceio",
    "America/Manaus", "America/Montevideo", "America/Noronha",
    "America/Porto_Velho", "America/Punta_Arenas", "America/Recife",
    "America/Rio_Branco", "America/Santarem", "America/Santiago",
    "America/Sao_Paulo", "Antarctica/Casey", "Antarctica/Davis",
    "Antarctica/DumontDUrville", "Antarctica/Macquarie", "Antarctica/Mawson",
    "Antarctica/McMurdo", "Antarctica/Palmer", "Antarctica/Rothera",
    "Antarctica/Syowa", "Antarctica/Troll", "Antarctica/Vostok",
    "Asia/Dili", "Asia/Jakarta", "Asia/Jayapura",
    "Asia/Makassar", "Asia/Pontianak", "Atlantic/South_Georgia",
    "Atlantic/St_Helena", "Atlantic/Stanley", "Australia/Adelaide",
    "Australia/Brisbane", "Australia/Broken_Hill", "Australia/Darwin",
    "Australia/Eucla", "Australia/Hobart", "Australia/Lindeman",
    "Australia/Lord_Howe", "Australia/Melbourne", "Australia/Perth",
    "Australia/Sydney", "Indian/Antananarivo", "Indian/Chagos",
    "Indian/Christmas", "Indian/Cocos", "Indian/Comoro",
    "Indian/Kerguelen", "Indian/Mahe", "Indian/Mauritius",
    "Indian/Mayotte", "Indian/Reunion", "Pacific/Apia",
    "Pacific/Auckland", "Pacific/Bougainville", "Pacific/Chatham",
    "Pacific/Easter", "Pacific/Efate", "Pacific/Fakaofo",
    "Pacific/Fiji", "Pacific/Funafuti", "Pacific/Galapagos",
    "Pacific/Gambier", "Pacific/Guadalcanal", "Pacific/Kanton",
    "Pacific/Marquesas", "Pacific/Nauru", "Pacific/Niue",
    "Pacific/Norfolk", "Pacific/Noumea", "Pacific/Pago_Pago",
    "Pacific/Pitcairn", "Pacific/Port_Moresby", "Pacific/Rarotonga",
    "Pacific/Tahiti", "Pacific/Tongatapu", "Pacific/Wallis",
})


TROPIC_ZONES = frozenset({
    "Africa/Abidjan", "Africa/Accra", "Africa/Addis_Ababa",
    "Africa/Asmara", "Africa/Bamako", "Africa/Bangui",
    "Africa/Banjul", "Africa/Bissau", "Africa/Blantyre",
    "Africa/Brazzaville", "Africa/Bujumbura", "Africa/Conakry",
    "Africa/Cotonou", "Africa/Dakar", "Africa/Dar_es_Salaam",
    "Africa/Djibouti", "Africa/Douala", "Africa/Freetown",
    "Africa/Harare", "Africa/Juba", "Africa/Kampala",
    "Africa/Khartoum", "Africa/Kigali", "Africa/Kinshasa",
    "Africa/Lagos", "Africa/Libreville", "Africa/Lome",
    "Africa/Luanda", "Africa/Lubumbashi", "Africa/Lusaka",
    "Africa/Malabo", "Africa/Mogadishu", "Africa/Monrovia",
    "Africa/Nairobi", "Africa/Ndjamena", "Africa/Niamey",
    "Africa/Nouakchott", "Africa/Ouagadougou", "Africa/Porto-Novo",
    "Africa/Sao_Tome", "Africa/Windhoek", "America/Anguilla",
    "America/Antigua", "America/Araguaina", "America/Aruba",
    "America/Bahia", "America/Bahia_Banderas", "America/Barbados",
    "America/Belem", "America/Belize", "America/Boa_Vista",
    "America/Bogota", "America/Campo_Grande", "America/Cancun",
    "America/Caracas", "America/Cayenne", "America/Cayman",
    "America/Costa_Rica", "America/Cuiaba", "America/Curacao",
    "America/Dominica", "America/Eirunepe", "America/El_Salvador",
    "America/Fortaleza", "America/Grand_Turk", "America/Grenada",
    "America/Guadeloupe", "America/Guatemala", "America/Guayaquil",
    "America/Guyana", "America/Havana", "America/Jamaica",
    "America/Kralendijk", "America/La_Paz", "America/Lima",
    "America/Lower_Princes", "America/Maceio", "America/Managua",
    "America/Manaus", "America/Marigot", "America/Martinique",
    "America/Mazatlan", "America/Merida", "America/Montserrat",
    "America/Noronha", "America/Panama", "America/Paramaribo",
    "America/Port-au-Prince", "America/Port_of_Spain", "America/Porto_Velho",
    "America/Puerto_Rico", "America/Recife", "America/Rio_Branco",
    "America/San_Salvador", "America/Santarem", "America/Santo_Domingo",
    "America/St_Barthelemy", "America/St_Kitts", "America/St_Lucia",
    "America/St_Thomas", "America/St_Vincent", "America/Tegucigalpa",
    "America/Tortola", "Asia/Aden", "Asia/Bangkok",
    "Asia/Brunei", "Asia/Colombo", "Asia/Dhaka",
    "Asia/Dili", "Asia/Ho_Chi_Minh", "Asia/Jakarta",
    "Asia/Jayapura", "Asia/Kolkata", "Asia/Kuala_Lumpur",
    "Asia/Kuching", "Asia/Makassar", "Asia/Manila",
    "Asia/Phnom_Penh", "Asia/Pontianak", "Asia/Singapore",
    "Asia/Vientiane", "Asia/Yangon", "Atlantic/Cape_Verde",
    "Atlantic/St_Helena", "Australia/Darwin", "Australia/Lindeman",
    "Indian/Antananarivo", "Indian/Chagos", "Indian/Christmas",
    "Indian/Cocos", "Indian/Comoro", "Indian/Mahe",
    "Indian/Maldives", "Indian/Mauritius", "Indian/Mayotte",
    "Indian/Reunion", "Pacific/Apia", "Pacific/Bougainville",
    "Pacific/Chuuk", "Pacific/Efate", "Pacific/Fakaofo",
    "Pacific/Fiji", "Pacific/Funafuti", "Pacific/Galapagos",
    "Pacific/Gambier", "Pacific/Guadalcanal", "Pacific/Guam",
    "Pacific/Honolulu", "Pacific/Kanton", "Pacific/Kiritimati",
    "Pacific/Kosrae", "Pacific/Kwajalein", "Pacific/Majuro",
    "Pacific/Marquesas", "Pacific/Nauru", "Pacific/Niue",
    "Pacific/Noumea", "Pacific/Pago_Pago", "Pacific/Palau",
    "Pacific/Pohnpei", "Pacific/Port_Moresby", "Pacific/Rarotonga",
    "Pacific/Saipan", "Pacific/Tahiti", "Pacific/Tarawa",
    "Pacific/Tongatapu", "Pacific/Wake", "Pacific/Wallis",
})


WIN_ZONES = {
    "AUS Central Standard Time": "Australia/Darwin", "AUS Eastern Standard Time": "Australia/Sydney",
    "Arab Standard Time": "Asia/Riyadh", "Arabian Standard Time": "Asia/Dubai",
    "Argentina Standard Time": "America/Argentina/Buenos_Aires", "Bangladesh Standard Time": "Asia/Dhaka",
    "Cen. Australia Standard Time": "Australia/Adelaide", "Central America Standard Time": "America/Guatemala",
    "E. Africa Standard Time": "Africa/Nairobi", "E. Australia Standard Time": "Australia/Brisbane",
    "E. South America Standard Time": "America/Sao_Paulo", "Hawaiian Standard Time": "Pacific/Honolulu",
    "India Standard Time": "Asia/Kolkata", "Magallanes Standard Time": "America/Punta_Arenas",
    "Malay Peninsula Standard Time": "Asia/Kuala_Lumpur", "Mauritius Standard Time": "Indian/Mauritius",
    "Montevideo Standard Time": "America/Montevideo", "Myanmar Standard Time": "Asia/Yangon",
    "Namibia Standard Time": "Africa/Windhoek", "Nepal Standard Time": "Asia/Kathmandu",
    "New Zealand Standard Time": "Pacific/Auckland", "Pacific SA Standard Time": "America/Santiago",
    "Paraguay Standard Time": "America/Asuncion", "Réunion Standard Time": "Indian/Reunion",
    "SA Eastern Standard Time": "America/Cayenne", "SA Pacific Standard Time": "America/Bogota",
    "SA Western Standard Time": "America/La_Paz", "SE Asia Standard Time": "Asia/Bangkok",
    "Singapore Standard Time": "Asia/Singapore", "South Africa Standard Time": "Africa/Johannesburg",
    "South America Standard Time": "America/Sao_Paulo", "Sri Lanka Standard Time": "Asia/Colombo",
    "Sudan Standard Time": "Africa/Khartoum", "Tasmania Standard Time": "Australia/Hobart",
    "Venezuela Standard Time": "America/Caracas", "W. Australia Standard Time": "Australia/Perth",
    "West Central Africa": "Africa/Luanda",
}

